/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        "surface": "#f8f9ff",
        "on-tertiary-fixed-variant": "#6e3900",
        "on-primary": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-dim": "#cbdbf5",
        "primary-fixed-dim": "#68dba9",
        "on-error-container": "#93000a",
        "surface-bright": "#f8f9ff",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#002116",
        "error-container": "#ffdad6",
        "secondary-container": "#a6f2d1",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#8bd6b6",
        "on-secondary-fixed-variant": "#00513b",
        "tertiary-fixed-dim": "#ffb77d",
        "background": "#f8f9ff",
        "outline": "#6d7a72",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary-container": "#fffbff",
        "on-surface": "#0b1c30",
        "primary-fixed": "#85f8c4",
        "on-secondary": "#ffffff",
        "primary-container": "#00855d",
        "secondary": "#1b6b51",
        "surface-tint": "#006c4a",
        "on-background": "#0b1c30",
        "tertiary": "#8d4b00",
        "on-primary-fixed-variant": "#005137",
        "surface-variant": "#d3e4fe",
        "error": "#ba1a1a",
        "primary": "#006948",
        "tertiary-container": "#b15f00",
        "inverse-surface": "#213145",
        "on-primary-container": "#f5fff7",
        "outline-variant": "#bccac0",
        "on-primary-fixed": "#002114",
        "on-tertiary-fixed": "#2f1500",
        "inverse-primary": "#68dba9",
        "tertiary-fixed": "#ffdcc3",
        "on-secondary-container": "#237157",
        "surface-container-highest": "#d3e4fe",
        "surface-container-high": "#dce9ff",
        "surface-container": "#e5eeff",
        "secondary-fixed": "#a6f2d1",
        "on-surface-variant": "#3d4a42"
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        "headline-sm": ["16px", { "lineHeight": "24px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["15px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-md": ["13px", { "lineHeight": "18px", "fontWeight": "500" }],
        "body-sm": ["12px", { "lineHeight": "18px", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "display": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.025em", "fontWeight": "800" }],
        "headline-md": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "headline-lg": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-eyebrow": ["11px", { "lineHeight": "16px", "letterSpacing": "0.06em", "fontWeight": "700" }],
        "title-kpi": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-xs": ["11px", { "lineHeight": "14px", "fontWeight": "600" }]
      }
    }
  },
  plugins: []
};
