import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Bar, BarChart, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useScenarios } from '../context/ScenarioContext';

export default function CompareScenarios() {
  const { scenarios } = useScenarios();
  const [ids, setIds] = useState([scenarios[0]?.id, scenarios[1]?.id]);
  if (scenarios.length < 2) return <div className="mx-auto max-w-7xl"><h1 className="text-3xl font-bold">Compare scenarios</h1><section className="mt-6 rounded-xl border border-blue-200 bg-blue-50 p-8 text-center"><h2 className="text-xl font-semibold">More scenarios needed</h2><p className="mt-3 text-slate-600">You need at least 2 saved scenarios to perform a side-by-side comparison.</p><Link to="/build" className="mt-6 inline-block rounded-lg bg-emerald-600 px-5 py-3 font-semibold text-white">Build a Scenario</Link></section></div>;
  const chosen = ids.map((id) => scenarios.find((scenario) => scenario.id === id)).filter(Boolean);
  const [a, b] = chosen;
  const metrics = [['Yield (t/ha)', 'yield'], ['Water use (mm)', 'water'], ['Total cost (₹)', 'cost'], ['Revenue (₹)', 'revenue'], ['Profit (₹)', 'profit'], ['Risk level', 'riskLevel']];
  const data = chosen.map((scenario) => ({ name: scenario.name, yield: scenario.result.yield, water: scenario.result.water }));
  return <div className="mx-auto max-w-7xl"><h1 className="text-3xl font-bold">Compare scenarios</h1><div className="mt-5 grid gap-3 sm:grid-cols-2">{ids.map((id, index) => <select key={index} className="rounded-lg border border-slate-300 bg-white p-3" value={id} onChange={(e) => setIds((current) => current.map((value, itemIndex) => itemIndex === index ? e.target.value : value))}>{scenarios.map((scenario) => <option key={scenario.id} value={scenario.id}>{scenario.name}</option>)}</select>)}</div><section className="mt-6 overflow-x-auto rounded-xl border border-slate-200 bg-white p-5"><table className="w-full text-left"><thead><tr><th>Metric</th>{chosen.map((scenario) => <th key={scenario.id}>{scenario.name}</th>)}</tr></thead><tbody>{metrics.map(([label, key]) => <tr key={key} className="border-t"><td className="py-3 text-slate-600">{label}</td>{chosen.map((scenario) => <td key={scenario.id} className="font-semibold">{key === 'riskLevel' ? scenario.result[key] : scenario.result[key].toLocaleString('en-IN')}</td>)}</tr>)}</tbody></table></section><div className="mt-6 h-80 rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Yield and water use</h2><ResponsiveContainer width="100%" height="90%"><BarChart data={data}><XAxis dataKey="name" /><YAxis /><Tooltip /><Legend /><Bar dataKey="yield" name="Yield (t/ha)" fill="#059669" /><Bar dataKey="water" name="Water Use (mm)" fill="#0284c7" /></BarChart></ResponsiveContainer></div>{a && b && <article className="mt-6 rounded-xl border border-blue-100 bg-blue-50 p-6"><h2 className="text-xl font-semibold">What changed?</h2><div className="mt-3 flex flex-wrap gap-5"><span>{b.result.yield - a.result.yield > 0 ? '↑' : '↓'} {Math.abs(b.result.yield - a.result.yield).toFixed(1)} t/ha yield</span><span>{b.result.water - a.result.water > 0 ? '↑' : '↓'} {Math.abs(b.result.water - a.result.water)} mm water</span><span>{b.result.risk - a.result.risk > 0 ? '↑' : '↓'} {Math.abs(b.result.risk - a.result.risk)} risk points</span></div><p className="mt-3 text-slate-700">Primary driver: {b.result.explanation}</p></article>}</div>;
}
