import { Link } from 'react-router-dom';
import { useScenarios } from '../context/ScenarioContext';

export default function Dashboard() {
  const { scenarios, deleteScenario } = useScenarios();
  const active = scenarios.at(-1);

  if (!active) return <div className="mx-auto max-w-7xl"><h1 className="text-3xl font-bold">Farm decision overview</h1><section className="mt-6 rounded-xl border border-emerald-200 bg-emerald-50 p-8 text-center shadow-sm"><h2 className="text-xl font-semibold">No scenarios saved yet</h2><p className="mx-auto mt-3 max-w-xl text-slate-600">No scenarios saved yet. Start modeling your farm decisions by building your first scenario.</p><Link to="/build" className="mt-6 inline-block rounded-lg bg-emerald-600 px-5 py-3 font-semibold text-white">Build a Scenario</Link></section></div>;

  const kpis = [['Yield', `${active.result.yield} t/ha`], ['Water used', `${active.result.water} mm`], ['Total cost', `₹${active.result.cost.toLocaleString('en-IN')}`], ['Risk level', active.result.riskLevel]];
  return <div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-semibold text-emerald-700">{active.inputs.location} • {active.inputs.crop} • {active.inputs.area} acres</p><h1 className="text-3xl font-bold">Farm decision overview</h1></div><div className="flex gap-3"><Link to="/build" className="rounded-lg bg-emerald-600 px-4 py-2 text-white">+ New Scenario</Link><Link to="/compare" className="rounded-lg border border-slate-300 px-4 py-2">Compare Scenarios</Link></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{kpis.map(([label, value]) => <article key={label} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></article>)}</div><section className="mt-6 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold">Saved scenarios</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-slate-500"><tr><th className="p-3">Name</th><th>Crop</th><th>Yield</th><th>Risk</th><th /></tr></thead><tbody>{scenarios.map((scenario) => <tr key={scenario.id} className="border-b border-slate-100"><td className="p-3 font-medium">{scenario.name}</td><td>{scenario.inputs.crop}</td><td>{scenario.result.yield} t/ha</td><td><span className="rounded-full bg-amber-100 px-2 py-1 text-amber-800">{scenario.result.riskLevel}</span></td><td className="py-2 text-right"><Link className="mr-3 text-emerald-700" to="/compare">Compare</Link><button className="text-red-600" onClick={() => deleteScenario(scenario.id)}>Delete</button></td></tr>)}</tbody></table></div></section></div>;
}
