import { Link } from 'react-router-dom';
import { useScenarios } from '../context/ScenarioContext';

export default function History() {
  const { scenarios, saveScenario, deleteScenario } = useScenarios();
  if (scenarios.length === 0) return <div className="mx-auto max-w-6xl"><h1 className="text-3xl font-bold">Scenario history</h1><section className="mt-6 rounded-xl border border-slate-200 bg-white p-8 text-center shadow-sm"><h2 className="text-xl font-semibold">No scenario history yet</h2><p className="mt-3 text-slate-600">Build your first farm scenario to see it here.</p><Link to="/build" className="mt-6 inline-block rounded-lg bg-emerald-600 px-5 py-3 font-semibold text-white">Build a Scenario</Link></section></div>;

  return <div className="mx-auto max-w-6xl"><h1 className="text-3xl font-bold">Scenario history</h1><div className="mt-6 grid gap-4 md:grid-cols-2">{scenarios.map((scenario) => <article key={scenario.id} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between"><h2 className="font-semibold">{scenario.name}</h2><span className="rounded-full bg-amber-100 px-2 py-1 text-xs">{scenario.result.riskLevel}</span></div><p className="mt-2 text-sm text-slate-500">{scenario.inputs.location} • {scenario.inputs.crop} • {scenario.inputs.area} acres</p><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><span>Yield: <b>{scenario.result.yield} t/ha</b></span><span>Water: <b>{scenario.result.water} mm</b></span><span>Cost: <b>₹{scenario.result.cost.toLocaleString('en-IN')}</b></span><span>Profit: <b>₹{scenario.result.profit.toLocaleString('en-IN')}</b></span></div><div className="mt-5 flex gap-3 text-sm"><Link to="/compare" className="text-emerald-700">View / Compare</Link><button onClick={() => saveScenario({ ...scenario, name: `${scenario.name} copy` })} className="text-blue-700">Duplicate</button><button onClick={() => deleteScenario(scenario.id)} className="text-red-600">Delete</button></div></article>)}</div></div>;
}
